reagent-project/reagent-forms

resources/reagent-forms.css
src/reagent_forms/core.cljs
src/reagent_forms/datepicker.cljs

The datepicker was broken, compressing days to a single column and not displaying the popover correctly. This PR should fix that.

Stylesheet fixes for the datepicker

---

README.md
src/reagent_forms/core.cljs

A user might want to use a different datatype or format in the doc than a field uses natively to better adapt it to his application. This PR provides two new optional functions that can be provided to the field templates to accommodate that need. Their use is explained in the README.

Added adapters for custom storage formats.

---

src/reagent_forms/core.cljs

We are using namespaced keywords to keep unified attribute names from datomic through to our clients, and the id->path function was accidentally dropping the namespace.  This fixes it.
Thanks for the great library!  We had a half baked version of the same type of thing, and it's been really nice using reagent-forms so far.

Making id->path retain the namespace of type keyword.

---

README.md
resources/reagent-forms.css
src/reagent_forms/core.cljs

changed reagent-forms.css to include example classes
changed typeahead to include support for user definition of css class
for input, ul, li, highlight
changed typeahead to include esc key support

changed documentation to provide examples using new css class params

---

src/reagent_forms/core.cljs

also suppressed default behavior of up and down keys (they were shifting the cursor position in the input element)

Fixed bug in list rendering which was causing infinite calls :data-source function

---

forms-example/project.clj

Version 0.3.9 doesn't include 25190f8ca3ad98b85336c8d2a49960ca5b5fbaab, which leads to the compiled example failing with the same error as in #56.

update example reagent-forms dependency to 0.5.1

---

src/reagent_forms/core.cljs

I made this addition as I couldn't see another way to get bootstrap's [form validation state](http://getbootstrap.com/css/#forms-control-validation) styles working.
The implementation is based on `event` in `alert`, but with semantics like `visible?`. The `valid?` attribute should be a decision function that takes the document atom and returns, for each validation state of the container's children, the name of a class corresponding to that state. The children can then inherit the styles of these classes. For example:
```clojure
[:form.form-horizontal
[:div.form-group {:field  :container
:valid? #(case (:test-input %)
"yes" "has-success"
"no" "has-error"
"maybe" "has-warning"
nil)}
[:label.control-label.col-sm-2 {:for :test-input} "yes or no?"]
[:div.col-sm-9 [:input.form-control {:field …
```

Add validation class attribute to container field

---

src/reagent_forms/core.cljs

Here are a few changes which I had to make to get the typeahead to work well for me:
* support overriding the per-result DOM in the dropdown (bootstrap 3 css seems to want an `<a>` tag in each element, or nothing is shown)
* support returning a vector e.g. `[name id]` from data-source
* set `style` attr on the dropdown for showing/hiding (bootstrap3 css has a rule `display:none;` on the class `.dropdown` which breaks the typeahead before these changes)
* allow differentiating between a value set by typing in the text input, and a value set by the user choosing an option from the dropdown (optional `choice-fn`)
* TAB key chooses selected item
* focusing the text input, by default, clears it
With these changes, I find it feels very nice and looks great with bootstrap (and I'm using FlatUI …

Typeahead usability improvements

---

src/reagent_forms/core.cljs

This is a minor fix for the new typeahead functionality. In 0.5.3, when `:result-fn` isn't defined otherwise, react will choke with `Invariant Violation: cljs$core$identity.render(): A valid ReactComponent must be returned. You may have returned undefined, an array or some other invalid object.`

explicitly evaluate the typeahead result-fn

---

forms-example/project.clj

Updates dependencies in the example project so it uses the current `reagent-forms` release.

Update dependencies in forms-example project

---

project.clj
src/reagent_forms/core.cljs

I have a complex data structure with maps within a vector that I cannot access with the current string-based path parsing.  E.g.
{:foo [{:bar 42 :baz 43} ...]}
This allows you to bring your own path to access like:
[:foo 0 :bar]
I also considered parsing integer indexes and converting those (:foo.0.bar) but this seemed more flexible.

Allow BYO id paths

---

src/reagent_forms/datepicker.cljs

I noticed the month names and shortened day0of-week names were hardcoded in the components. They now use the dates object.
I would really like to be able to use a custom provided `dates` map for i18 purposes (we are using reagent-forms in production). This is a small step towards that feature request because the names are now encapsulated in one place.

remove duplication of month/day names

---

src/reagent_forms/datepicker.cljs

Fix for issue #85.
i. Change last-date and prev-date functions to return a vector of size 3 containing year, month and day and avoid the error: No item 2 in vector of length 2
ii. Update to not save the date on year and month selections to avoid invalid dates e.g. 31/Feb/2016

Datepicker boundary issue fix

---

src/reagent_forms/core.cljs

as the current value for datepicker fields. Right now if a date is already present the formatted field will show this defined date, the datepicker itself will start with the current calender month, ignoring the defined date.

If a date is defined use it instead of the current day

---

src/reagent_forms/core.cljs
src/reagent_forms/datepicker.cljs

Datepicker now accepts `:lang` which takes a keyword which maps to built-in
languages like :en-US. 
Currently provides English, Russian, French, Spanish, Portuguese and Finnish mappings. Also, the `:lang` key accepts a language hash-map with correct format.
Language hash-maps must define `:first-day` key which allow choosing arbritrary first day of the week
by index starting from Sunday as 0. Choosing :first-day 1 would render monday as the first day of the week.
Also moved functions related to `gen-days` above it for clarity.
Example usage:
```clojure
{:field :datepicker :id :date :date-format "yyyy/mm/dd" :inline true :lang
{:days        ["First" "Second" "Third" "Fourth" "Fifth" "Sixth" "Seventh"]
:days-short  ["1st" "2nd" "3rd" "4th" "5th" "6th" "7th"]
:months      ["Month-one" …
```

Issue #84: L10n

---

src/reagent_forms/core.cljs

This fixes issue #97 
As far as I could see, the 'checked' attribute of the checkbox was not wired to the state atom, so that if you would reset it, the checkbox would not "un-check".
I used merge there because we only want to add "checked" if the checkbox is meant to be checked as the absence of that attribute is the only correct way of saying it shouldn't.
This should now work fine when you clear the form:
```clojure
(defn annotate-pane []
(let [doc (atom nil)]
(fn []
[:div
[:p (str @doc)]
[bind-fields
[:input.form-control {:field :checkbox :id :first-name}]
doc]
[:button
{:on-click #(reset! doc nil)}
"clear"]])))
```

Add 'checked' attribute to checkbox component. Fix gh-97.

---

README.md
src/reagent_forms/core.cljs

With optional key :closeable? (defaults to true) you can remove the
close button element. This allows having :field :alert on elements on
which a close button is undesireable.

Allow removing the close button on an alert component

---

README.md

Looks like I rushed the documentation a little.

Fix typos and move the new block added to alert section a little up

---

src/reagent_forms/core.cljs

This change in React https://github.com/facebook/react/issues/5013
causes the warning message if the value of an input is null.

Set value to an empty string in case the date is nil

---

src/reagent_forms/core.cljs

This fixes the case when option `clear-on-focus` is set to true. Without
it clicking on a candidate clears the value in the input.

preventDefault on a click on a candidate in typeahead

---

src/reagent_forms/core.cljs

If not when a typeahead is for example used inside a form, then choosing a
candidate by ret key can result in a submit.

When choosing a candidate with ret key preventDefault

---

.gitignore
README.md
dev/public/index.html
dev/reagent_forms/page.cljs
project.clj
src/reagent_forms/core.cljs

Suggested additions to typeahead:
- If the `:data-source` function returns a single element then this is automatically selected. This is not configurable as currently implemented, it seemed a subtle enough change not to upset anyone, but could be optional of course
- If the typeahead list is long enough to scroll, the list doesn't autoscroll with the keyboard. Added code to fix this.
- I wanted the full list to become visible without actually typing anything. I added code so down-arrow will display the list, which it does by calling `:data-source` passing the keyword `:all`. This isn't a breaking change, in that an empty list would be returned anyway if the client doesn't implement this.
This mod leaves the way open for adding a dropdown button, should someone want that.
- If the …

Typeahead new features

---

src/reagent_forms/core.cljs
src/reagent_forms/macros.clj

`:disabled` should support boolean value or a function (similarly to `:visible?` - see #59)
This PR also adds (previously missing) support for `:disabled` in either of the two forms to the following components:
- Typeahead
- Datepicker
Still unsupported elements:
- `[:option]`
-  `[:button]`s inside `btn-group` 
I'm not sure how to handle those yet. The structure is more complicated - I could use clojure.walk but I'm trying to think of a simpler solution without additional dependency. I'll revisit when I have time again.

:disabled should support functions

---

src/reagent_forms/core.cljs
src/reagent_forms/macros.clj

Following up on #125 this PR adds support for `:disabled` on inner `:*-select` or `:list` fields.
I ended up using `clojure.walk` after all as this is the only way I can think of to traverse the unknown structures (we can't assume users won't add additional markup around inner buttons/divs/lis inside `.button-group`). I'm open to suggestions.

Support for :disabled on select-groups/lists

---

src/reagent_forms/core.cljs
src/reagent_forms/macros.clj
test/reagent_forms/core_test.cljs

This PR allows a user to pass a map of `get/save!/update!` functions to override the default `bind-fields` behavior for those events (as per #127). In particular, this will allow the user to make `reagent-forms` compatible with libraries like `re-frame`. For example:
```clojure
[bind-fields
[:input {:field :text :id :xyz}]
{:get (fn [id] (deref (re-frame/subscribe [id])))
:save! (fn [id v] (re-frame/dispatch [id v]))
:update! (fn [id v] (re-frame/dispatch [id v]))}]
```
In this version, `bind-fields` no longer supports the `& events` part since it seems redundant - the functions would have the same signature as the functions in above map.
In addition, `visible?` will now support passing an id to be used by the specified `:get` function.
In above example, an input like this:
```clojure …
```

Add a version of `bind-fields` accepting a map of `get/update!/save!` functions

---

src/reagent_forms/core.cljs
test/reagent_forms/core_test.cljs

As per discussion in #138, `wrap-fns` is required for `save-fn`, `in-fn` and similar to work.

Wrap-fns for re-frame mode

---

README.md

The re-frame example has excess closing w/o matching opening bracket.

Unbalanced vector in re-frame example

---

src/reagent_forms/datepicker.cljs

Added a missing 10th month short name (Loka) to the datepicker's fi-FI locale map.

Fix a reagent-project/reagent-forms issue (#145)
